// <auto-generated />
using System;
using BodyLife.Crm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BodyLife.Crm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BodyLifeDbContext))]
    [Migration("20260713144951_AddMembershipExtensionDays")]
    partial class AddMembershipExtensionDays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bodylife")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Audit.BusinessAuditEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("ActorAccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("actor_account_type");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_role");

                    b.Property<string>("AfterSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_summary");

                    b.Property<string>("BeforeSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_summary");

                    b.Property<bool>("ChangedAfterClose")
                        .HasColumnType("boolean")
                        .HasColumnName("changed_after_close");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntryOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_origin");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RelatedEntityRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("related_entity_refs");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_correlation_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorAccountId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_business_audit_entries_actor_timeline");

                    b.HasIndex("EntityType", "EntityId", "RecordedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_business_audit_entries_entity_timeline");

                    b.ToTable("business_audit_entries", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_business_audit_entries_action_type_not_empty", "length(btrim(action_type)) > 0");

                            t.HasCheckConstraint("ck_business_audit_entries_actor_account_type", "actor_account_type in ('owner', 'named_admin', 'shared_reception_admin')");

                            t.HasCheckConstraint("ck_business_audit_entries_actor_role", "actor_role in ('owner', 'admin')");

                            t.HasCheckConstraint("ck_business_audit_entries_correlation_not_empty", "length(btrim(request_correlation_id)) > 0");

                            t.HasCheckConstraint("ck_business_audit_entries_entity_type_not_empty", "length(btrim(entity_type)) > 0");

                            t.HasCheckConstraint("ck_business_audit_entries_entry_origin", "entry_origin in ('normal', 'manual_backfill', 'paper_fallback', 'future_import')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientCardAssignmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_account_id");

                    b.Property<string>("CardNumberNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_number_normalized");

                    b.Property<string>("CardNumberRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_number_raw");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("EndedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_account_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByAccountId")
                        .HasDatabaseName("ix_client_card_assignments_assigned_by_account_id");

                    b.HasIndex("CardNumberNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_client_card_assignments_current_card")
                        .HasFilter("is_current");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ux_client_card_assignments_current_client")
                        .HasFilter("is_current");

                    b.HasIndex("EndedByAccountId")
                        .HasDatabaseName("ix_client_card_assignments_ended_by_account_id");

                    b.HasIndex("ClientId", "AssignedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_client_card_assignments_client_history");

                    b.ToTable("client_card_assignments", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_client_card_assignments_ended_after_assigned", "ended_at is null or ended_at >= assigned_at");

                            t.HasCheckConstraint("ck_client_card_assignments_lifecycle", "(\n    is_current\n    and ended_at is null\n    and ended_by_account_id is null\n    and end_reason is null\n)\nor (\n    not is_current\n    and ended_at is not null\n    and ended_by_account_id is not null\n    and end_reason is not null\n    and length(btrim(end_reason)) > 0\n)");

                            t.HasCheckConstraint("ck_client_card_assignments_normalized_not_empty", "length(btrim(card_number_normalized)) > 0");

                            t.HasCheckConstraint("ck_client_card_assignments_raw_not_empty", "length(btrim(card_number_raw)) > 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_full_name");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operational_status");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneLastFour")
                        .HasColumnType("text")
                        .HasColumnName("phone_last4");

                    b.Property<string>("PhoneNormalized")
                        .HasColumnType("text")
                        .HasColumnName("phone_normalized");

                    b.Property<string>("PhoneRaw")
                        .HasColumnType("text")
                        .HasColumnName("phone_raw");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId")
                        .HasDatabaseName("ix_clients_created_by_account_id");

                    b.HasIndex("NormalizedFullName")
                        .HasDatabaseName("ix_clients_normalized_full_name");

                    b.HasIndex("PhoneNormalized")
                        .HasDatabaseName("ix_clients_phone_normalized")
                        .HasFilter("phone_normalized is not null");

                    b.HasIndex("PhoneLastFour", "OperationalStatus")
                        .HasDatabaseName("ix_clients_phone_last4_status")
                        .HasFilter("phone_last4 is not null");

                    b.ToTable("clients", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_clients_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_clients_normalized_full_name_not_empty", "length(btrim(normalized_full_name)) > 0");

                            t.HasCheckConstraint("ck_clients_operational_status", "operational_status in ('active', 'inactive')");

                            t.HasCheckConstraint("ck_clients_patronymic_not_empty", "patronymic is null or length(btrim(patronymic)) > 0");

                            t.HasCheckConstraint("ck_clients_phone_fields_consistent", "(phone_raw is null and phone_normalized is null and phone_last4 is null)\nor (\n    phone_raw is not null\n    and length(btrim(phone_raw)) > 0\n    and phone_normalized is not null\n    and phone_normalized ~ '^[0-9]{4,}$'\n    and phone_last4 is not null\n    and phone_last4 ~ '^[0-9]{4}$'\n    and phone_last4 = right(phone_normalized, 4)\n)");

                            t.HasCheckConstraint("ck_clients_surname_not_empty", "length(btrim(surname)) > 0");

                            t.HasCheckConstraint("ck_clients_updated_after_created", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.DuplicateWarningAcknowledgementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("AcknowledgedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_account_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("MatchedClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_client_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("WarningType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("warning_type");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByAccountId")
                        .HasDatabaseName("ix_duplicate_warning_acks_actor");

                    b.HasIndex("ClientId", "AcknowledgedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_duplicate_warning_acks_client_timeline");

                    b.HasIndex("MatchedClientId", "AcknowledgedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_duplicate_warning_acks_match_timeline");

                    b.ToTable("duplicate_warning_acknowledgements", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_duplicate_warning_acknowledgements_distinct_clients", "client_id <> matched_client_id");

                            t.HasCheckConstraint("ck_duplicate_warning_acknowledgements_reason_not_empty", "length(btrim(reason)) > 0");

                            t.HasCheckConstraint("ck_duplicate_warning_acknowledgements_warning_type", "warning_type in ('duplicate_phone', 'similar_name')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Idempotency.CommandIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_kind");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("AuditEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_entry_id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("command_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<string>("EntryOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_origin");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("PrimaryEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_entity_id");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_correlation_id");

                    b.Property<Guid?>("RereadTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("reread_target_id");

                    b.Property<string>("ResultFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("result_fingerprint");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_command_idempotency_keys_expires_at");

                    b.HasIndex("CommandName", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_command_idempotency_keys_command_key");

                    b.ToTable("command_idempotency_keys", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_command_idempotency_keys_account_kind_not_empty", "length(btrim(account_kind)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_actor_role_not_empty", "length(btrim(actor_role)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_command_name_not_empty", "length(btrim(command_name)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_completed_after_created", "completed_at is null or completed_at >= created_at");

                            t.HasCheckConstraint("ck_command_idempotency_keys_completed_status_has_time", "(status = 'started') or completed_at is not null");

                            t.HasCheckConstraint("ck_command_idempotency_keys_correlation_not_empty", "length(btrim(request_correlation_id)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_entry_origin", "entry_origin in ('normal', 'manual_backfill', 'paper_fallback', 'future_import')");

                            t.HasCheckConstraint("ck_command_idempotency_keys_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_command_idempotency_keys_key_not_empty", "length(btrim(idempotency_key)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_started_not_completed", "(status <> 'started') or completed_at is null");

                            t.HasCheckConstraint("ck_command_idempotency_keys_status", "status in ('started', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.MembershipTypes.MembershipTypeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisitsLimit")
                        .HasColumnType("integer")
                        .HasColumnName("visits_limit");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Id")
                        .HasDatabaseName("ix_membership_types_active_issue_order")
                        .HasFilter("is_active");

                    b.ToTable("membership_types", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_membership_types_comment_not_empty", "comment is null or length(btrim(comment)) > 0");

                            t.HasCheckConstraint("ck_membership_types_currency_canonical", "length(btrim(price_currency)) > 0 and price_currency = upper(btrim(price_currency))");

                            t.HasCheckConstraint("ck_membership_types_duration_positive", "duration_days > 0");

                            t.HasCheckConstraint("ck_membership_types_lifecycle", "(\n    is_active\n    and deactivated_at is null\n)\nor (\n    not is_active\n    and deactivated_at is not null\n    and deactivated_at >= created_at\n    and deactivated_at <= updated_at\n)");

                            t.HasCheckConstraint("ck_membership_types_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_membership_types_price_non_negative", "price_amount >= 0");

                            t.HasCheckConstraint("ck_membership_types_updated_after_created", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_membership_types_visits_non_negative", "visits_limit >= 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.IssuedMembershipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BaseEndDate")
                        .HasColumnType("date")
                        .HasColumnName("base_end_date");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("DurationDaysSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days_snapshot");

                    b.Property<Guid?>("EntryBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_batch_id");

                    b.Property<string>("EntryOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_origin");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_account_id");

                    b.Property<Guid>("MembershipTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_type_id");

                    b.Property<decimal>("PriceAmountSnapshot")
                        .HasColumnType("numeric")
                        .HasColumnName("price_amount_snapshot");

                    b.Property<string>("PriceCurrencySnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency_snapshot");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TypeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name_snapshot");

                    b.Property<int>("VisitsLimitSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("visits_limit_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("IssuedByAccountId")
                        .HasDatabaseName("ix_issued_memberships_issued_by_account_id");

                    b.HasIndex("MembershipTypeId")
                        .HasDatabaseName("ix_issued_memberships_membership_type_id");

                    b.HasIndex("ClientId", "StartDate", "IssuedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_issued_memberships_client_timeline");

                    b.ToTable("issued_memberships", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_issued_memberships_base_end_date", "base_end_date = start_date + (duration_days_snapshot - 1)");

                            t.HasCheckConstraint("ck_issued_memberships_comment_not_empty", "comment is null or length(btrim(comment)) > 0");

                            t.HasCheckConstraint("ck_issued_memberships_currency_snapshot_canonical", "length(btrim(price_currency_snapshot)) > 0 and price_currency_snapshot = upper(btrim(price_currency_snapshot))");

                            t.HasCheckConstraint("ck_issued_memberships_duration_snapshot_positive", "duration_days_snapshot > 0");

                            t.HasCheckConstraint("ck_issued_memberships_entry_origin", "entry_origin in ('normal', 'manual_backfill', 'paper_fallback', 'future_import')");

                            t.HasCheckConstraint("ck_issued_memberships_price_snapshot_non_negative", "price_amount_snapshot >= 0");

                            t.HasCheckConstraint("ck_issued_memberships_status", "status in ('active', 'canceled', 'corrected')");

                            t.HasCheckConstraint("ck_issued_memberships_type_name_snapshot_not_empty", "length(btrim(type_name_snapshot)) > 0");

                            t.HasCheckConstraint("ck_issued_memberships_visits_snapshot_non_negative", "visits_limit_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipExtensionDayRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ExtensionDate")
                        .HasColumnType("date")
                        .HasColumnName("extension_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_label");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "ExtensionDate")
                        .HasDatabaseName("ix_membership_extension_days_active_membership_date")
                        .HasFilter("is_active");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("ix_membership_extension_days_source");

                    b.HasIndex("MembershipId", "ExtensionDate", "SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_membership_extension_days_membership_date_source");

                    b.ToTable("membership_extension_days", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_membership_extension_days_source_label_not_empty", "length(btrim(source_label)) > 0");

                            t.HasCheckConstraint("ck_membership_extension_days_source_type_not_empty", "length(btrim(source_type)) > 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipOpeningStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DeclaredNegativeBalance")
                        .HasColumnType("integer")
                        .HasColumnName("declared_negative_balance");

                    b.Property<int>("DeclaredRemainingVisits")
                        .HasColumnType("integer")
                        .HasColumnName("declared_remaining_visits");

                    b.Property<Guid?>("EntryBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_batch_id");

                    b.Property<string>("EntryOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_origin");

                    b.Property<DateOnly?>("KnownEffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("known_effective_end_date");

                    b.Property<int?>("KnownExtensionDays")
                        .HasColumnType("integer")
                        .HasColumnName("known_extension_days");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateOnly>("OpeningAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("opening_as_of_date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_account_id");

                    b.Property<Guid>("RecordedSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_session_id");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .IsUnique()
                        .HasDatabaseName("ux_membership_opening_states_active_membership")
                        .HasFilter("status = 'active'");

                    b.HasIndex("RecordedByAccountId")
                        .HasDatabaseName("ix_membership_opening_states_recorded_by_account_id");

                    b.HasIndex("RecordedSessionId")
                        .HasDatabaseName("ix_membership_opening_states_recorded_session_id");

                    b.HasIndex("MembershipId", "OpeningAsOfDate", "RecordedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_membership_opening_states_membership_timeline");

                    b.ToTable("membership_opening_states", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_membership_opening_states_entry_origin", "entry_origin in ('manual_backfill', 'paper_fallback', 'future_import')");

                            t.HasCheckConstraint("ck_membership_opening_states_known_end_not_before_opening", "known_effective_end_date is null or known_effective_end_date >= opening_as_of_date");

                            t.HasCheckConstraint("ck_membership_opening_states_known_extension_days_non_negative", "known_extension_days is null or known_extension_days >= 0");

                            t.HasCheckConstraint("ck_membership_opening_states_negative_balance_consistent", "declared_negative_balance = greatest(0::bigint, -(declared_remaining_visits::bigint))");

                            t.HasCheckConstraint("ck_membership_opening_states_reason_not_empty", "length(btrim(reason)) > 0");

                            t.HasCheckConstraint("ck_membership_opening_states_source_reference_not_empty", "length(btrim(source_reference)) > 0");

                            t.HasCheckConstraint("ck_membership_opening_states_status", "status in ('active', 'canceled', 'corrected')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipStateCacheRecord", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<int>("CountedVisits")
                        .HasColumnType("integer")
                        .HasColumnName("counted_visits");

                    b.Property<DateOnly>("EffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_end_date");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("integer")
                        .HasColumnName("extension_days");

                    b.Property<DateOnly?>("FirstNegativeVisitDate")
                        .HasColumnType("date")
                        .HasColumnName("first_negative_visit_date");

                    b.Property<Guid?>("FirstNegativeVisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_negative_visit_id");

                    b.Property<DateTimeOffset?>("LastCountedVisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_counted_visit_at");

                    b.Property<int>("NegativeBalance")
                        .HasColumnType("integer")
                        .HasColumnName("negative_balance");

                    b.Property<DateTimeOffset>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<int>("RecalculationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("recalculation_version");

                    b.Property<int>("RemainingVisits")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_visits");

                    b.HasKey("MembershipId");

                    b.HasIndex("EffectiveEndDate")
                        .HasDatabaseName("ix_membership_state_cache_effective_end_date");

                    b.HasIndex("LastCountedVisitAt")
                        .HasDatabaseName("ix_membership_state_cache_last_counted_visit_at");

                    b.HasIndex("NegativeBalance")
                        .HasDatabaseName("ix_membership_state_cache_negative_balance_open")
                        .HasFilter("negative_balance > 0");

                    b.HasIndex("RemainingVisits")
                        .HasDatabaseName("ix_membership_state_cache_remaining_visits");

                    b.ToTable("membership_state_cache", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_membership_state_cache_counted_visits_non_negative", "counted_visits >= 0");

                            t.HasCheckConstraint("ck_membership_state_cache_extension_days_non_negative", "extension_days >= 0");

                            t.HasCheckConstraint("ck_membership_state_cache_negative_balance_consistent", "negative_balance = greatest(0::bigint, -(remaining_visits::bigint))");

                            t.HasCheckConstraint("ck_membership_state_cache_recalculation_version_positive", "recalculation_version > 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login_name");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_login_name");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("AccountId");

                    b.HasIndex("NormalizedLoginName")
                        .IsUnique()
                        .HasDatabaseName("ux_account_credentials_normalized_login_name");

                    b.ToTable("account_credentials", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_account_credentials_login_name_not_empty", "length(btrim(login_name)) > 0");

                            t.HasCheckConstraint("ck_account_credentials_normalized_login_name_not_empty", "length(btrim(normalized_login_name)) > 0");

                            t.HasCheckConstraint("ck_account_credentials_password_hash_not_empty", "length(btrim(password_hash)) > 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("AccountType")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_single_owner")
                        .HasFilter("account_type = 'owner'");

                    b.HasIndex("IsActive", "AccountType")
                        .HasDatabaseName("ix_accounts_active_type");

                    b.ToTable("accounts", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_account_type", "account_type in ('owner', 'named_admin', 'shared_reception_admin')");

                            t.HasCheckConstraint("ck_accounts_account_type_role", "(account_type = 'owner' and role = 'owner')\nor (account_type in ('named_admin', 'shared_reception_admin') and role = 'admin')");

                            t.HasCheckConstraint("ck_accounts_active_deactivated_at", "(is_active and deactivated_at is null) or (not is_active and deactivated_at is not null)");

                            t.HasCheckConstraint("ck_accounts_deactivated_at_after_created", "deactivated_at is null or deactivated_at >= created_at");

                            t.HasCheckConstraint("ck_accounts_display_name_not_empty", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_accounts_role", "role in ('owner', 'admin')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.SessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExpiresAt")
                        .HasDatabaseName("ix_sessions_active_account_expires_at")
                        .HasFilter("ended_at is null");

                    b.ToTable("sessions", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_ended_at_after_started", "ended_at is null or ended_at >= started_at");

                            t.HasCheckConstraint("ck_sessions_expires_after_started", "expires_at > started_at");

                            t.HasCheckConstraint("ck_sessions_last_seen_after_started", "last_seen_at >= started_at");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientCardAssignmentRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("AssignedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("EndedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.DuplicateWarningAcknowledgementRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("AcknowledgedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_warning_acks_actor");

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_warning_acks_client");

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("MatchedClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_warning_acks_matched_client");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.IssuedMembershipRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.ClientsSearch.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("IssuedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.MembershipTypes.MembershipTypeRecord", null)
                        .WithMany()
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipExtensionDayRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.Memberships.IssuedMembershipRecord", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipOpeningStateRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.Memberships.IssuedMembershipRecord", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.SessionRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordedSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipStateCacheRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.Memberships.IssuedMembershipRecord", "Membership")
                        .WithOne()
                        .HasForeignKey("BodyLife.Crm.Infrastructure.Persistence.Memberships.MembershipStateCacheRecord", "MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", "Account")
                        .WithOne()
                        .HasForeignKey("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.SessionRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
