// <auto-generated />
using System;
using BodyLife.Crm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BodyLife.Crm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BodyLifeDbContext))]
    [Migration("20260709143654_AddAccountCredentials")]
    partial class AddAccountCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bodylife")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.Idempotency.CommandIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_kind");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("AuditEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_entry_id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("command_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<string>("EntryOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_origin");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("PrimaryEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_entity_id");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_correlation_id");

                    b.Property<Guid?>("RereadTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("reread_target_id");

                    b.Property<string>("ResultFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("result_fingerprint");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_command_idempotency_keys_expires_at");

                    b.HasIndex("CommandName", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_command_idempotency_keys_command_key");

                    b.ToTable("command_idempotency_keys", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_command_idempotency_keys_account_kind_not_empty", "length(btrim(account_kind)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_actor_role_not_empty", "length(btrim(actor_role)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_command_name_not_empty", "length(btrim(command_name)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_completed_after_created", "completed_at is null or completed_at >= created_at");

                            t.HasCheckConstraint("ck_command_idempotency_keys_completed_status_has_time", "(status = 'started') or completed_at is not null");

                            t.HasCheckConstraint("ck_command_idempotency_keys_correlation_not_empty", "length(btrim(request_correlation_id)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_entry_origin", "entry_origin in ('normal', 'manual_backfill', 'paper_fallback', 'future_import')");

                            t.HasCheckConstraint("ck_command_idempotency_keys_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_command_idempotency_keys_key_not_empty", "length(btrim(idempotency_key)) > 0");

                            t.HasCheckConstraint("ck_command_idempotency_keys_started_not_completed", "(status <> 'started') or completed_at is null");

                            t.HasCheckConstraint("ck_command_idempotency_keys_status", "status in ('started', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login_name");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_login_name");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("AccountId");

                    b.HasIndex("NormalizedLoginName")
                        .IsUnique()
                        .HasDatabaseName("ux_account_credentials_normalized_login_name");

                    b.ToTable("account_credentials", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_account_credentials_login_name_not_empty", "length(btrim(login_name)) > 0");

                            t.HasCheckConstraint("ck_account_credentials_normalized_login_name_not_empty", "length(btrim(normalized_login_name)) > 0");

                            t.HasCheckConstraint("ck_account_credentials_password_hash_not_empty", "length(btrim(password_hash)) > 0");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("AccountType")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_single_owner")
                        .HasFilter("account_type = 'owner'");

                    b.HasIndex("IsActive", "AccountType")
                        .HasDatabaseName("ix_accounts_active_type");

                    b.ToTable("accounts", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_account_type", "account_type in ('owner', 'named_admin', 'shared_reception_admin')");

                            t.HasCheckConstraint("ck_accounts_account_type_role", "(account_type = 'owner' and role = 'owner')\nor (account_type in ('named_admin', 'shared_reception_admin') and role = 'admin')");

                            t.HasCheckConstraint("ck_accounts_active_deactivated_at", "(is_active and deactivated_at is null) or (not is_active and deactivated_at is not null)");

                            t.HasCheckConstraint("ck_accounts_deactivated_at_after_created", "deactivated_at is null or deactivated_at >= created_at");

                            t.HasCheckConstraint("ck_accounts_display_name_not_empty", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_accounts_role", "role in ('owner', 'admin')");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.SessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StartedAt")
                        .HasDatabaseName("ix_sessions_active_account_started_at")
                        .HasFilter("ended_at is null");

                    b.ToTable("sessions", "bodylife", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_ended_at_after_started", "ended_at is null or ended_at >= started_at");

                            t.HasCheckConstraint("ck_sessions_last_seen_after_started", "last_seen_at >= started_at");
                        });
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", "Account")
                        .WithOne()
                        .HasForeignKey("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountCredentialRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.SessionRecord", b =>
                {
                    b.HasOne("BodyLife.Crm.Infrastructure.Persistence.UsersRoles.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
